title: Musings of shadowhand
email: hello@shadowhand.me
description: >- # this means to ignore newlines until "baseurl:"
  Shadowhand aka Woody Gilk is a humane developer from Minnesota.
url: "https://blog.shadowhand.me"
twitter_username: shadowhand
github_username:  shadowhand

# Enable post excerpts
show_excerpts: false

# Enable comments
disqus:
  shortname: shadowhand

# Style
markdown: kramdown
theme: minima

# URLs
permalink: /:title/

# Excludes
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
